### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by optimalisatie** [FancyGrid/FancyTrack#1]
Hi!

I found your library via [EchoJS](http://www.echojs.com/) and was wondering if it would be possible to make the source code available.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by MikeTatsky** [comment]
Ok, we will provide it soon.

**Comment by mathpere** [comment]
+1

**Comment by nevf** [comment]
+1

**Comment by NickThomson1977** [comment]
FancyTrack/client/fancytrack.js

Done
