### ISSUE TITLE
Package as module and publish to npm?

### ISSUE THREAD

**Issue by voxpelli** [FancyGrid/FancyTrack#2]
Would be lovely to be able to pull in this package as a npm dependency and to be able to include it in eg. a Browserify build.

Could you add a [universal module definition](https://github.com/umdjs/umd), a `package.json` and publish it to npm?

**Comment by MikeTatsky** [comment]
Sure, in nearest time.

**Comment by MikhailTatsky** [comment]
Done

**Comment by MikeTatsky** [comment]
Needs to fix.

**Comment by MikeTatsky** [comment]
Sorry for delay.
It was enabled usual AMD 
https://github.com/umdjs/umd/blob/master/templates/amdWeb.js

Please check it out.
It is ok?
